blank_issues_enabled: true
contact_links:
  - name: Questions and support
    url: https://github.com/aryaemami59/.github/blob/main/.github/SUPPORT.md
    about: Read the support guidelines before opening an issue.
  - name: Report a security vulnerability
    url: https://github.com/aryaemami59/.github/blob/main/.github/SECURITY.md
    about: Please do not open a public issue for security reports.
